apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgAM8vaRv1FMM5d5jVRirwtjqrgccinwnteholjOdekPyqDcCaKG9BbGDOU9bNB3MjI1xywOqUULFd/XpspBQV9JzdWEs+OFCex9cOymAlPiFwt6QVBoQ74PX9J5edDcEh8lPxFERSrafYNr0AOU5RaTKWyxjQvHC4Klgne1aVYhND7qkF7iuvkAZ5ToSBOQLWbU1l2k4jiUkHFo+qlc7HLsHGhLmV19g0lhexdVjW+u4nOcqWpgOyJBHM8mKTssm/LAIMwLDGDn3gCyb+BwRnmcGTnX5MSLwMDgBQ1n2dlydVz2+JH2H4vQ6FIudkxBjkQNtYI9HDrdyjYyktPL+aUFxcYaUY3wvvAAVcTzvMFPcqEHEd+f2vGkTVryesLE9ir46gXZRnNDJeYJfFO3maCYgzRdKkD2E+6TvoMIYfopSgF9ttJYhBW8I/G0LrBv7UyejO7XDLr+P4WH0kxWhifHd7EjFBYrQvGVOtjR5wpGNmRkZuxyrtFK2++P6FCRLNV1w6XT11WF0T6x7KCD66zURDKPYY2zv7FbJ0sZKVwD/hBpMNMqXH/TNqy5n1jIR55Gd39XKLuJGBNluL1EfcTbd1TkUUEVySUTsitztdld2uTlU3Pd+ha8b8+W3kpM1adfUYCwICcUZn1XwU9gIc8dSFRcgdFBkvdEZ2yxPTMTAgsijwtyIFcmh7DteS8DI25v5bXVONsdAk6GCjnupMoojEVLoOA7okciEROw/8yvsN5sFLmMnD4oWWc0NBNgT1EjmR4lPmREsegkPBceVX+FX4NuFKssaLP1b0MYdJ5zGOeXJ9ODkS9RI0G5Bf0JS5GqtyMQs5Yi28p/k0O2+4WdXNU5GGH+7LMTkVZTb2UZN+zg5QsEXODnIuVICf3sZjSxEnQY+EgIg8o7vnH0dkIoookHxhLgfN6EXW2GBd8WkxFfp0Kh7x3sMf03iNii1pYVCXVSuTvGosagZeiLc7ZECBfrtvUPIq8n525mxRylZQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

