apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgCGW86NdENxtMaYFT84JLcsskQ/OaA/n6TAS9sfZS4pP9T2BvvueuWFQB5zfEjqnoMktCh7PAfcGQKPaU51H/4fXwvbxkR2H+6jDxS27qxPQ3xdMVrenNQ97cM7KOcFzjmViKy+tkg2ChGqiaVTKII/jz18PYlW9ElCjNKLVy48zC/NsAPrM8TgGThxeDVbajoGT+stgavNipiu3sCBqarAyH7kpdSZzKQ99GPTy6YVtj1FrS5COBdWIXfE/Ym+/oShDgtMI5btIyTek3bVAdkUST8d3xbp7EQyjVcdM7OB/yd0jkFKnbt9Z52EnR3XDW3mn1o0jpFq89SaBZdqjXbJjpw8xkNigf7mRULEDhH0ReR4ajJRcbV75DqKK+HJm4Fj47ENFOJG3ExpYW1pXDLWuxVax/fAIpVxW5i8dnX5ihLEtdl3F+mJYPzQWM2vlBTo2NNiTS+TE9x7PauP3GiMNG6Qjgoxh4PYn3R8H36ZGjBKy6oqgxI0nktgrCyGoZoZKx7tXS0IjUvGQI7RNB+3qe4Qzt5uNx/GtfoDZ4ysSH1Roo6p9Y7B/z/ex+oMZJbaIyHSgk4Xhad2KgGoCY7wyT4h8xxeGbdMnXKqq+Geo9dsa60+ioirEtuIa16om1XEUA1mJzXWrB9hU3uOsEXelUEWAHfy+syk8SFEN9NO16eLR1prLdfFiD40otRnHQBo5EaKGuu7OBaJ9aVlru9UlMZSBgdTVvAu1I7ng2x6d+x5M4LCKRwRLm69zaTXGdQY/LtjTncSqLVKKO+OaRB6BuNsFzk1ISxt7v7tbluERWR2CNtwq/dDtR0I2NOKcWSmJeQEDj1r6en86wi5ejPwKxj70Lx9nip5oz+zHIEGcsZera/+dNo2j6wClaQ9cNujvcoOfAxbg17gwxysf/6TgXd8WizZglSTBH4FD5G9jVn24uUV1Z5iUluzT1qB2o7nutwN7/ou+TSYQnsXocURbQ8xgjqe6weSN2mW4y5yEg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

