apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgCMv8cy9D8TahAVc+miK5vFXjFtxZRqVgwO0kuWYVmk4VV5QndSXG7AMpXbmRXbh0SkhIEYiKn72b8CuzPon9b/EEurczAzYFp09iaOa4JqqK49OqRtMiEKsuTEDFYYjh9VvWD9K9ftPCPbh7HTxaUYy3Eu5duyxBwafXyI5PgLZz3LmAjDUO6IxRfANPOHC0yG0VXw6SjopQhaZZdldjxcFi5PzhFTRtTBAKiPJILVfYrpvNSol2BTvTg/1gqUDgdwCnEp4UFAyR3SfRoYuVIlsTQdb7Hiokvisc8SqEyUQgdG4Kb7nDZFmpIkA8NwMvds8cxlcoc81UhRsA1PpnKAUrECRfa1nBoMPLfO+ARFBFgRD8AawYavSpKQfiNyF14wVfEqGZdQcJN9dYU0AT/fm5fMh5eu2psEw5T+BiwIagta6FoFnHbkMVpdR7v+eEDEUCxRyJPYem5jJJfJGZLEwtvZCeRdXNbWeRJa3zv6BmOkv5NeVtXL/AuXaFYaA77E2gkGBe9NDBYwQurq678bEpbUtISbp7sGh3Bk6xcOnGDAZdOnkNQxAUaUfGBjVSUPMdk6R4ffddCuPwlAFRRlGZD1BWCXS2OtdMNgsLd1ihlD1Hhap3O+qbjgsYuGWCePnSthtPq+PrBMv3tyhicPhe3PwEOOICPRojvuLsiM2tLgqHaiXNveb3IorVAJL8p8ce6ytdzk8m5NNyeu1Uz9yHa0jN/SBcNhBEgAS/XLw+79hvMRTzPogaUH1K0Sm8oUOo4S+ESvFp2OFISExQxBloH9/Nz4kKFLQ3m0H4tnY0zHjuqIybUtWpb03zdM9k3bbGk3HsDyBZW0r6XWnafW7RW+97q13Ldo2Jz4g0/GquXF+h/DdyIQkUDGvLyK9Jez3JkkFAvwwseLZ8luFQhtU3PW8J/ou6S8bLzMf6Se/g2mRnPgn5L4cv/iRhiJQ1tItOOhGTIRrwRp7pkrJzvY9eM8sJUDS7EsOSXGNF5g3Q==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

