apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgCHfsHTXcRsFmaFyTFI4UNQ2jPqSd34h0wthqhmb1AVtY4QYSUU3lnxfIvw6CLa1AtRdPUzPdK8g5PKEavG9IH2K44y6bNyYeuuw3RpiofQIwijOBEIOX1F6pKmpe2TQ6qZB9UtTW48Dv03NAEvmNe/4yiGwIumu6oCmb+BXC6SC/JsY98mvAf8w9KOXumJUD6TiWyf5LG9UjUnFhl8+wgshhtTH8YgIEKGWpIFDPfAMSIQyIme0tCQdKOU/bX2oNxvVbKti+30zkx1PVVNMnId4eLrPkNTd3qZQ80NmI1mFRqbfG0z3oJ1bj6MLpKjdXAzOfuec7psM4/MeZrCYe1m7G6oX1IQF29Z+H80XI4F3SOD8aKOdp05IDCRLEvmAEBkjuo9zYaBM598m2S8KhYErGB2HY/nHh+LcH86cLyqeW6/dWVEVc+aUHnrsDL+Dv7ErlE8h3dbUoTQVQM61GeIPV28O82Rljt/FmDfuxNR0+xN9ui8q50fp+6FWH0Oza1qagORK77AYbLyGLbwqeiNELbFo6Tyv7WiXSVpPhMvCYU0IoSusdGlvPjGwxrayXWBCejuD5yHeqdzEL+CUVjWXv4xJHLTxUJ53QekNlyXkLesUHK2zYGTKQUzOZPQWw49sTlV2TRIS4Do/Edh8FjThwY9MJwMMJdJENiS6PHwuIAHq8fLA0bpLn89oB7SsSEzQ7CdiIOidPF8ZsW8x9rcj144nNfuMZZ8qH5gZHO3gpna5MlD74PWXmhD0vkxDWxE61LEVYa5n+oRTAAC2H0kKRgAsHNlVWiTw2Bk+9B7DPs2cge1IOGmaMFaCZvD4L8aT1UDjsN7B5PMRO2Ic//Syl9WyCafbO3yaW0yoAzIpkxipy1k+q5dlJ8tLpa+KRNDCdrxJIkj/ese15c8Vpd7CXat5OnS0EqGcLlnvocyG/f5s9ZyB3sY4TbsX5JTyjYFciBiF6Wo5qIun1BbcimO/bgB0W0Aq7/gWxsbE7nK/Q==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

